services:
  api:
    image: sleevedmanager/atlas:v1.4.0
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - default
      - sleeved-network

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - /mnt/securedata/atlas/db:/var/lib/mysql
      - /mnt/securedata/atlas/dumps/sleeved_db_structure_dump.sql:/docker-entrypoint-initdb.d/sleeved_db_structure_dump.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
          "--silent",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - default
      - looter-network
    container_name: sleeved-db

networks:
  default:
  sleeved-network:
    external: true
  looter-network:
    external: true
