version: "3"

tasks:
  default:
    desc: Display available commands
    cmds:
      - task --list-all
    silent: true

  # Database commands
  db:import:
    desc: Import database from dump file
    cmds:
      - echo "Importing database from dump file..."
      - |
        source .env && \
        echo "🔄 Starting import... " && \
        (docker compose exec -T mysql mysql -uroot -p"$MYSQL_ROOT_PASSWORD" $DB_DATABASE < /mnt/securedata/atlas/dumps/sleeved_db_data_dump.sql 2>&1) && \
        echo "✅ Import completed with success !"

  db:migrate:
    desc: Run database migrations
    cmds:
      - docker compose exec api node ace migration:run --force

  db:rollback:
    desc: Rollback the last migration
    cmds:
      - docker compose exec api node ace migration:rollback --force

  # Setup commands
  setup:
    desc: Setup the application environment
    cmds:
      - task: networks:create
      - task: build
      - task: start

  # Networks commands
  networks:create:
    desc: Create the external network if it does not exist
    cmds:
      - docker network inspect sleeved-network || docker network create sleeved-network
      - docker network inspect looter-network || docker network create looter-network

  networks:info:
    desc: Display network information
    cmds:
      - docker network ls
      - docker network inspect sleeved-network
      - docker network inspect looter-network

  networks:remove:
    desc: Remove the external network
    cmds:
      - docker network rm sleeved-network
      - docker network rm looter-network

  # Application commands
  start:
    desc: Start all services
    cmds:
      - docker compose up -d

  stop:
    desc: Stop all services
    cmds:
      - docker compose down

  restart:
    desc: Restart all services
    cmds:
      - task: stop
      - task: start

  build:
    desc: Build the application
    cmds:
      - docker compose build

  rebuild:
    desc: Rebuild and restart
    cmds:
      - task: stop
      - task: build
      - task: start
      - task: logs

  logs:
    desc: Show application logs
    cmds:
      - docker compose logs -f api
