name: 🚀 Deploy Warden to VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Warden
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3

      - name: Upload infra files to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "./warden/*"
          target: "/srv/apps/warden"

      - name: Deploy container on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /srv/apps/warden
            echo "📦 Stopping old containers..."
            docker-compose down
            echo "📥 Pulling latest image..."
            docker-compose pull
            echo "🚀 Starting service..."
            task setup
            echo "💾 Migrate database..."
            task db:migrate
            echo "✅ Warden deployed successfully!"
