name: 🔧 Update Looter Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Looter version to deploy (ex: v1.2.3)"
        required: true

  repository_dispatch:
    types: [update-looter-tag]

jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace tag in docker-compose.yml
        run: |
          sed -i "s|looter:[a-zA-Z0-9.\-]*|looter:${{ github.event.inputs.version || github.event.client_payload.version }}|g" ./looter/docker-compose.yml

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-looter-${{ github.event.inputs.version || github.event.client_payload.version }}
          title: "🚀 Deploy looter ${{ github.event.inputs.version || github.event.client_payload.version }}"
          body: "Auto-generated PR to update `looter` image tag to `${{ github.event.inputs.version || github.event.client_payload.version }}`"
          commit-message: "chore: update looter image to ${{ github.event.inputs.version || github.event.client_payload.version }}"
